<?php
require_once  __DIR__ . '/config/cdb.php';
require_once __DIR__ . '/components/head.php'; 
 ?>
  
<form action="ajoutspec.php" method="post">
<div>
    <label for="spec">Spécialités</label>
    <input type="text" name="spec" id="spec" >
</div>
<br>
<div>   
    <button type="submit">Enregistrer les modifications</button>  
    
</div>
</form>

<?php require_once __DIR__ . '/components/footer.php'; ?>
